name: Ryuzenn-Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
      - name: Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github.stats.svg 
          user: kutemeikito
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          repositories_affiliations: Ryuzenn
          
      - name: Skyline
        uses: lowlighter/metrics@latest
        with:
          filename: github.skyline.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2020
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          
      - name: Anime
        uses: lowlighter/metrics@latest
        with:
          filename: anilis.anime.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 1
          plugin_anilist_user: ryuzenn
          
      - name: Manga
        uses: lowlighter/metrics@latest
        with:
          filename: anilis.manga.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites, reading
          plugin_anilist_limit: 1
          plugin_anilist_user: ryuzenn
          
      - name: Characters
        uses: lowlighter/metrics@latest
        with:
          filename: anilis.character.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22
          plugin_anilist_user: ryuzenn
          
          